### ISSUE TITLE
[bug] view is weird in Safari Browser

### ISSUE THREAD

**Issue by Isaac-Lee** [qkrdmstlr3/techstack-generator#7]
### Font Error?
- [ ] Different Font in Safari

The font in `JS`, `TS` icon is weird

<img width="150" alt="JS, TS font" src="https://user-images.githubusercontent.com/49810053/168441070-cf8e3e60-42d4-4dff-bae5-83f4b7370539.png">
And also font of `raspberry pi` icon as well

<img width="150" alt="R PI font" src="https://user-images.githubusercontent.com/49810053/168441115-fc936bdb-77a7-4a8b-ab2b-f7ef07680f36.png">

### Overall View
- [x] 'gap' property not working in Safari

And for the last the overall view is different from when I use Chrome.

<img width="1500" alt="overall view" src="https://user-images.githubusercontent.com/49810053/168441342-bf6f542c-c77c-4409-810a-327e434d3002.png">
The column is 5 whitch is 4 when I view with Chrome.

**Comment by qkrdmstlr3** [comment]
wow~~~ Thank you! Maybe I'll fix it after the first semester is over. I'm too busy😢

**Comment by Isaac-Lee** [comment]
Sure! Take your time.
I will find a way to fix this also.

**Comment by Isaac-Lee** [comment]
> ### Font Error?

I think the font issue is occurring because there is no `font-family` property.
https://github.com/qkrdmstlr3/techstack-generator/blob/a18a88b99c25018443db66d75c0971dc8febad07/static/js-icon.svg?short_path=7349877#L56-L59
https://github.com/qkrdmstlr3/techstack-generator/blob/a18a88b99c25018443db66d75c0971dc8febad07/static/raspberrypi-icon.svg?short_path=af08f80#L58-L64
It makes to bring the default font family of each browser, witch is as follow.

![스크린샷 2022-05-17 오후 12 03 14](https://user-images.githubusercontent.com/49810053/168719766-ed0ba4d8-2325-4e79-96e5-72df0b249885.png)

So adding the `font-family` property may solve the first problem.

**Comment by Isaac-Lee** [comment]
> ### Overall View

The view issue is occurring from following errors.
https://github.com/qkrdmstlr3/techstack-generator/blob/a18a88b99c25018443db66d75c0971dc8febad07/src/components/templates/select/style.ts#L27-L33

The `gap` property is not working properly in Safari.
I test the code in Chrome with turning off the `gap` property and it looks the same.

I searched it out a bit and found that under Safari `14.1` the **"flex gap"** was not supported. My Safari version is `14.0.3` so.. the veiw was weird for me.

Still, it would be great for fix this bug in the future :)

**Comment by Isaac-Lee** [comment]
I am still working on this issue.
The `gap` property is not working fine after updating my Safari.

But still font issue is having some problems in Safari browser.

I found that the default font Chrome is using is `'Roboto'`.
So I tried to import the font like below to use in every browser(including Safari).

```css
@import url('https://fonts.googleapis.com/css2?family=Roboto:ital@1&amp;display=swap');
@font-face {
    font-family: 'Roboto';
    font-style: normal;
    font-weight: 400;
    src: local('Roboto'), local('Roboto-Regular'), 
    url(https://fonts.gstatic.com/s/roboto/v19/KFOmCnqEu92Fr1Mu7GxKKTU1Kvnz.woff2) format('woff2');
    unicode-range: U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF;
}
.js-text {
    font-size: 30px;
    font-family: 'Roboto';
    font-weight: bold;
}
```
Unfortunately, nothing changed...

<img width="112" alt="스크린샷 2022-07-03 오후 11 36 11" src="https://user-images.githubusercontent.com/49810053/177044578-4922a032-7a4e-4f39-9a2a-12423df9e25a.png">

I will keep working on this issue but I think it will take some time 🥲

plus: It is very interesting that the html text is using `Roboto` font, but SVG text does not. (super super weird)
